### ISSUE TITLE
Issue with using Django for loops

### ISSUE THREAD

**Issue by copyfactory** [wrabit/django-cotton#26]
When using a for loop in a component the .last and .first attributes do not work.

__infinity_scroll.cotton.html__
```html
<ul role="list" class="divide-y divide-gray/5">
  {% for item in items %}
    <li class="{{ class }}"
        <!--  doing 'forloop.last is True' also does not work    -->
        {% if forloop.last %} <-- does not work
                hx-get="{% url 'my-url' %}?page={{ page }}"
                hx-swap="afterend"
                hx-trigger="intersect once"
                <!--       This does oddly succesfully evaluate to True/False but the conditional above doesn't.         -->
                data-has-more="{{ forloop.last }}"
      {% endif %}>
      {{ slot }}
    </li>
  {% endfor %}
</ul>
```

__usage__

```html
<!--Events is a paginated queryset from the view.-->
<c-components.infinity-scroll :items="events"></c-components.infinity-scroll>

```

My assumption is that built-in template tags are being overridden. 

Perhaps https://docs.djangoproject.com/en/5.0/ref/templates/builtins/#for should be protected while building the component?

**Comment by wrabit** [comment]
@copyfactory Yes - have noticed this myself even this morning, a PR is going through now which should resolve it.

- #27

**Comment by wrabit** [comment]
This should be fixed in v0.9.11

**Comment by copyfactory** [comment]
Great thank you

**Comment by wrabit** [comment]
If you have a chance and is still possible, could you can see if this resolves #17 ?

**Comment by copyfactory** [comment]
Sure thing, just checked and unfortunately did not resolve #17
